/* @generated by spec-generation-agent. Edits are lost on the next run. */

import type { APIRequestContext } from "@playwright/test";
import { routes } from "./routes.js";

/** API object model generated from the target's OpenAPI operations. */
export class ApiObjects {
  constructor(
    private readonly context: APIRequestContext,
    private readonly defaultHeaders: Record<string, string> = {},
  ) {}

  /** POST /warehouses — Create Warehouse */
  async createWarehouseWarehousesPost(options?: Parameters<APIRequestContext["post"]>[1]) {
    return this.context.post(routes.createWarehouseWarehousesPost(), {
      ...options,
      headers: { ...this.defaultHeaders, ...(options?.headers as Record<string, string> | undefined) },
    });
  }
}
