/* @generated by spec-generation-agent. Edits are lost on the next run. */

/**
 * Every path the generated suite uses, named by the operation id it came from.
 *
 * A spec never writes a path itself: a path typed into a test is a guess, and a guess that
 * executes fails for the wrong reason. Everything here traces to the target's OpenAPI document.
 */
export const routes = {
  /** POST /warehouses — Create Warehouse */
  createWarehouseWarehousesPost: () => `/warehouses`,
  /** GET /warehouses/{warehouse_id} — Get Warehouse */
  getWarehouseWarehousesWarehouseIdGet: (warehouseId: string | number) => `/warehouses/${warehouseId}`,
} as const;
