/* @generated by spec-generation-agent, run golden-run. Edits are lost on the next run. */
/* Source: the manual test design. Every assertion below carries the expected result it came from. */
import { expect, test } from "../../fixtures/test.js";
import { ApiObjects } from "../_support/apiObjects.js";

test.describe("FDN-501", () => {
  test(
    "A warehouse is created",
    {
      annotation: [
        { type: "case", description: "TestCase:create-a-warehouse" },
        { type: "obligation", description: "create-a-warehouse.step-1 — The response status code is 201." },
        {
          type: "obligation",
          description: "create-a-warehouse.step-2 — The returned code matches the code that was sent.",
        },
      ],
    },
    async ({ apiContext }) => {
      // Preconditions the manual case assumes:
      //   The tester is signed in as a system administrator.
      // Test data, from the manual case.
      const code = "WH-01";
      const name = "Main warehouse";
      const address = "1 Dock Road";
      const timezone = "Europe/London";
      const administratorBearerToken = "test-token";
      let api = new ApiObjects(apiContext);

      const authenticationToken = administratorBearerToken;
      api = new ApiObjects(apiContext, { Authorization: `Bearer ${authenticationToken}` });

      // Step 1 — Send a create warehouse request with the test data.
      const created = await api.createWarehouseWarehousesPost({ data: { code, name, address, timezone } });
      const createdBody = await created.json();
      // create-a-warehouse.step-1 — The response status code is 201.
      expect(created.status()).toBe(201);
      // create-a-warehouse.step-2 — The returned code matches the code that was sent.
      expect(createdBody["code"]).toEqual(code);
    },
  );
});
