import { operationById, pathPlaceholders, screenByName, tableByName, type ApiOperation, type EvidenceCatalogue } from "../evidence/catalogue.js";
import { RenderError } from "../errors.js";
import type { IrAssertion, IrMatcher, IrOperation, IrValue, TestIr } from "../ir/testIr.js";
import type { NormalisedCase } from "../model/testCase.js";

/**
 * IR → TypeScript. The only place generated code is written.
 *
 * Deterministic and dull on purpose: the same IR renders to the same file, byte for byte, so a
 * diff between runs shows what the *plan* changed and nothing else. It makes no decisions — if the
 * IR does not say something, the renderer does not supply it; if the IR is unrenderable, that is a
 * bug in the policy that let it through, and it fails loudly rather than improvising.
 *
 * Routes never appear as literals. They are rendered into one generated `routes` module and
 * referenced from there, so a path exists in exactly one place and always traces to an operation id.
 */

export const GENERATED_MARKER = "@generated by spec-generation-agent";

export interface RenderedSpec {
  /** Relative to the target project, e.g. `tests/generated/api/FDN-501.spec.ts`. */
  file: string;
  contents: string;
  /** Cases in this file that were written as fixme, with the reasons. */
  fixmes: { caseId: string; reasons: string[] }[];
}

export interface RenderInput {
  testCase: NormalisedCase;
  ir: TestIr;
  gaps: string[];
}

const identifier = (value: string): string => {
  const cleaned = value.replace(/[^a-zA-Z0-9]+(.)?/g, (_match, next: string | undefined) => (next ? next.toUpperCase() : ""));
  return /^[a-zA-Z_]/.test(cleaned) ? cleaned : `_${cleaned}`;
};

const quote = (value: string): string => JSON.stringify(value);

/** A comment body that cannot end the comment it is in. */
const comment = (value: string): string => value.replace(/\*\//g, "*​/").replace(/\r?\n/g, " ");

/**
 * The story a case belongs to decides its file. A case tracing to nothing lands in `UNASSIGNED`,
 * visibly, rather than being scattered or dropped.
 */
export function specFileFor(testCase: NormalisedCase, layer: "api" | "ui" | "db"): string {
  const story = testCase.stories[0]?.replace(/^[A-Za-z]+:/, "") ?? "UNASSIGNED";
  return `tests/generated/${layer}/${story.replace(/[^A-Za-z0-9_.-]+/g, "-")}.spec.ts`;
}

/** The routes module: every path the suite uses, named by its operation id. */
export function renderRoutes(catalogue: EvidenceCatalogue, used: ReadonlySet<string>): string {
  const operations = catalogue.api.filter((operation) => used.has(operation.operationId)).sort((a, b) => a.operationId.localeCompare(b.operationId));

  const entries = operations.map((operation) => {
    const placeholders = pathPlaceholders(operation.pathTemplate);
    const name = identifier(operation.operationId);
    const template = `\`${operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, key: string) => `\${${identifier(key)}}`)}\``;
    const parameters = placeholders.map((placeholder) => `${identifier(placeholder)}: string | number`).join(", ");
    return [
      `  /** ${operation.method.toUpperCase()} ${operation.pathTemplate}${operation.summary ? ` — ${comment(operation.summary)}` : ""} */`,
      `  ${name}: (${parameters}) => ${template},`,
    ].join("\n");
  });

  return [
    `/* ${GENERATED_MARKER}. Edits are lost on the next run. */`,
    "",
    "/**",
    " * Every path the generated suite uses, named by the operation id it came from.",
    " *",
    " * A spec never writes a path itself: a path typed into a test is a guess, and a guess that",
    " * executes fails for the wrong reason. Everything here traces to the target's OpenAPI document.",
    " */",
    "export const routes = {",
    ...entries,
    "} as const;",
    "",
  ].join("\n");
}

/** Evidence-derived API object model. Specs call operations, never raw HTTP verbs or paths. */
export function renderApiObjects(catalogue: EvidenceCatalogue, used: ReadonlySet<string>): string {
  const operations = catalogue.api.filter((operation) => used.has(operation.operationId)).sort((a, b) => a.operationId.localeCompare(b.operationId));
  const methods = operations.flatMap((operation) => {
    const placeholders = pathPlaceholders(operation.pathTemplate);
    const parameters = placeholders.map((placeholder) => `${identifier(placeholder)}: string | number`);
    parameters.push(`options?: Parameters<APIRequestContext[${quote(operation.method)}]>[1]`);
    const routeArgs = placeholders.map(identifier).join(", ");
    return [
      `  /** ${operation.method.toUpperCase()} ${operation.pathTemplate}${operation.summary ? ` — ${comment(operation.summary)}` : ""} */`,
      `  async ${identifier(operation.operationId)}(${parameters.join(", ")}) {`,
      `    const response = await this.context.${operation.method}(routes.${identifier(operation.operationId)}(${routeArgs}), {` ,
      `      ...options,`,
      `      headers: { ...this.defaultHeaders, ...(options?.headers as Record<string, string> | undefined) },`,
      `    });`,
      `    await observeResponse(${quote(operation.operationId)}, response);`,
      `    return response;`,
      `  }`,
      ``,
    ];
  });

  return [
    `/* ${GENERATED_MARKER}. Edits are lost on the next run. */`,
    ``,
    `import type { APIRequestContext } from "@playwright/test";`,
    `import { observeResponse } from "./observations.js";`,
    `import { routes } from "./routes.js";`,
    ``,
    `/** API object model generated from the target's OpenAPI operations. */`,
    `export class ApiObjects {`,
    `  constructor(`,
    `    private readonly context: APIRequestContext,`,
    `    private readonly defaultHeaders: Record<string, string> = {},`,
    `  ) {}`,
    ``,
    ...methods,
    `}`,
    ``,
  ].join("\n");
}

/**
 * Which layer a plan is written in, decided by what it actually does rather than what it claims.
 *
 * A case that drives a screen is a UI spec even when it also calls the API or checks a row, because
 * the browser is the only thing that can perform the action. A database read can only observe, so
 * it never decides the layer.
 */
export function layerOf(ir: TestIr): "api" | "db" | "ui" {
  if (ir.ops.some((op) => op.kind === "ui.goto" || op.kind === "ui.act")) return "ui";
  return ir.ops.some((op) => op.kind === "api.request") ? "api" : "db";
}

/** Renders one story's worth of cases into one spec file. */
export function renderApiSpec(story: string, cases: readonly RenderInput[], catalogue: EvidenceCatalogue, runId: string): RenderedSpec {
  if (cases.length === 0) throw new RenderError(`Nothing to render for ${story}.`);

  const layers = cases.map((entry) => layerOf(entry.ir));
  const layer = layers.includes("ui") ? "ui" : layers.includes("api") ? "api" : "db";
  const usesApi = cases.some((entry) => entry.ir.ops.some((op) => op.kind === "api.request"));
  const usesDb = cases.some((entry) => entry.ir.ops.some((op) => op.kind === "db.read"));
  const usesUi = cases.some((entry) => entry.ir.ops.some((op) => op.kind === "ui.goto" || op.kind === "ui.act"));
  const usesUniqueData = cases.some((entry) => allValues(entry.ir).some((value) => "uniqueTestData" in value));

  const lines: string[] = [];
  const fixmes: RenderedSpec["fixmes"] = [];
  const push = (line = ""): number => lines.push(line);

  push(`/* ${GENERATED_MARKER}, run ${runId}. Edits are lost on the next run. */`);
  push(`/* Source: the manual test design. Every assertion below carries the expected result it came from. */`);
  push(`import { expect, test } from "../../fixtures/test.js";`);
  push(`import { observe } from "../_support/observations.js";`);
  if (usesUniqueData) push(`import { uniqueValue } from "../../support/testData.js";`);
  if (usesApi) push(`import { ApiObjects } from "../_support/apiObjects.js";`);
  if (usesDb) push(`import { dataIntegrity } from "../_support/db.js";`);
  if (usesUi) push(`import { pages } from "../_support/screens.js";`);
  push();
  push(`test.describe(${quote(story)}, () => {`);

  for (const entry of cases) {
    renderCase(entry, catalogue, lines, fixmes);
  }

  push(`});`);
  push();

  return {
    file: `tests/generated/${layer}/${story.replace(/[^A-Za-z0-9_.-]+/g, "-")}.spec.ts`,
    contents: lines.join("\n"),
    fixmes,
  };
}

function renderCase(entry: RenderInput, catalogue: EvidenceCatalogue, lines: string[], fixmes: RenderedSpec["fixmes"]): void {
  const { testCase, ir, gaps } = entry;
  const unautomatable = ir.unautomatable;
  const unavailableAuth = ir.ops.find((op) => op.kind === "auth.unavailable");
  const isFixme = unautomatable.length > 0 || unavailableAuth !== undefined;

  if (isFixme) {
    const reasons = unautomatable.map((item) => `${item.obligation}: ${item.reason}`);
    if (unavailableAuth?.kind === "auth.unavailable") reasons.push(`authentication: ${unavailableAuth.reason}`);
    fixmes.push({ caseId: testCase.caseId, reasons });
  }

  lines.push("");
  lines.push(`  ${isFixme ? "test.fixme" : "test"}(${quote(testCase.name)}, {`);
  lines.push(`    annotation: [`);
  lines.push(`      { type: "case", description: ${quote(testCase.caseId)} },`);
  for (const obligation of testCase.obligations) {
    lines.push(`      { type: "obligation", description: ${quote(`${obligation.id} — ${obligation.text}`)} },`);
  }
  for (const item of unautomatable) {
    lines.push(`      { type: "fixme-reason", description: ${quote(`${item.obligation}: ${item.reason}`)} },`);
  }
  if (unavailableAuth?.kind === "auth.unavailable") {
    lines.push(`      { type: "fixme-reason", description: ${quote(`authentication: ${unavailableAuth.reason}`)} },`);
  }
  for (const gap of gaps) {
    lines.push(`      { type: "evidence-gap", description: ${quote(gap)} },`);
  }
  lines.push(`    ],`);
  const fixtures = [
    ...(ir.ops.some((op) => op.kind === "ui.goto" || op.kind === "ui.act") ? ["page"] : []),
    ...(ir.ops.some((op) => op.kind === "api.request" || op.kind === "auth.api" || op.kind === "auth.header") ? ["apiContext"] : []),
  ];
  lines.push(`  }, async ({${fixtures.length > 0 ? ` ${fixtures.join(", ")} ` : ""}}) => {`);

  if (testCase.preconditions.length > 0) {
    lines.push(`    // Preconditions the manual case assumes:`);
    for (const precondition of testCase.preconditions) lines.push(`    //   ${comment(precondition)}`);
  }

  const data = testCase.testData.filter((datum) => usesTestData(ir, datum.name));
  const uniqueData = uniqueDataConstraints(ir, catalogue);
  if (data.length > 0) {
    lines.push(`    // Test data, from the manual case.`);
    for (const datum of data) {
      const maxLength = uniqueData.get(datum.name);
      lines.push(
        uniqueData.has(datum.name)
          ? `    const ${identifier(datum.name)} = uniqueValue(${quote(datum.value)}${maxLength === undefined ? "" : `, ${maxLength}`});`
          : `    const ${identifier(datum.name)} = ${quote(datum.value)};`
      );
    }
  }

  if (ir.ops.some((op) => op.kind === "api.request" || op.kind === "auth.api")) lines.push(`    let api = new ApiObjects(apiContext);`);
  const pageNames = [...new Set(ir.ops.flatMap((op) => (op.kind === "ui.goto" || op.kind === "ui.act" ? [op.screen] : [])))];
  for (const name of pageNames) lines.push(`    const ${identifier(name)}Page = pages.${identifier(name)}(page);`);

  // Response and row assertions hang off the operation they check. A UI assertion is about the page
  // after a step, so it hangs off the operation that came before it in the plan.
  const assertionsByOp = new Map<string, IrAssertion[]>();
  for (const assertion of ir.assertions) {
    const step = testCase.obligations.find((obligation) => obligation.id === assertion.obligation)?.stepNumber;
    const key = assertion.kind === "assert.ui.element" ? (lastOpBefore(ir, assertion, step) ?? ir.ops[0]!.id) : assertion.of;
    assertionsByOp.set(key, [...(assertionsByOp.get(key) ?? []), assertion]);
  }

  for (const op of ir.ops) {
    lines.push("");
    lines.push(`    await observe("step", { id: ${quote(op.id)}, kind: ${quote(op.kind)}, phase: "start" });`);
    const step = "step" in op && op.step ? testCase.steps.find((candidate) => candidate.stepNumber === op.step) : undefined;
    if (step) lines.push(`    // Step ${step.stepNumber} — ${comment(step.action)}`);

    if (op.kind === "auth.header") {
      lines.push(`    const authenticationToken = ${renderValue(op.token, ir)};`);
      lines.push(`    api = new ApiObjects(apiContext, { ${quote(op.headerName)}: \`${op.scheme} \${authenticationToken}\` });`);
    } else if (op.kind === "auth.api") {
      const operation = operationById(catalogue, op.operationId);
      if (!operation) throw new RenderError(`Authentication operation "${op.operationId}" is not in the evidence.`);
      const authRequest = { kind: "api.request" as const, id: op.id, operationId: op.operationId, body: op.body, evidenceRefs: op.evidenceRefs };
      lines.push(`    const ${identifier(op.id)} = ${renderRequest(authRequest, operation, ir)};`);
      lines.push(`    expect(${identifier(op.id)}.ok(), ${quote("Authentication request failed")}).toBe(true);`);
      lines.push(`    const ${identifier(op.id)}Body = await ${identifier(op.id)}.json();`);
      lines.push(`    const authenticationToken = ${fieldAccessor(identifier(op.id), op.tokenPath)};`);
      lines.push(`    expect(authenticationToken, ${quote("Authentication response did not contain a token")}).toBeTruthy();`);
      lines.push(`    api = new ApiObjects(apiContext, { ${quote(op.headerName)}: \`${op.scheme} \${String(authenticationToken)}\` });`);
    } else if (op.kind === "auth.unavailable") {
      lines.push(`    // Authentication unavailable: ${comment(op.reason)}`);
    } else if (op.kind === "ui.goto") {
      const screen = screenByName(catalogue, op.screen);
      if (!screen) throw new RenderError(`Screen "${op.screen}" is not in the approved contract; the policy should have rejected this plan.`);
      lines.push(`    await ${identifier(screen.name)}Page.goto();`);
    } else if (op.kind === "ui.act") {
      const screen = screenByName(catalogue, op.screen);
      if (!screen) throw new RenderError(`Screen "${op.screen}" is not in the approved contract; the policy should have rejected this plan.`);
      const locator = `${identifier(screen.name)}Page.${identifier(op.element)}`;
      const argument = op.value ? renderValue(op.value, ir) : "";
      lines.push(`    await ${locator}.${op.action}(${argument});`);
    } else if (op.kind === "db.read") {
      const table = tableByName(catalogue, op.table);
      if (!table) throw new RenderError(`Table "${op.table}" is not in the evidence; the policy should have rejected this plan.`);
      lines.push(`    const ${identifier(op.id)} = await dataIntegrity.findRows(${quote(table.name)}, [`);
      for (const predicate of op.where) {
        lines.push(`      { column: ${quote(predicate.column)}, op: ${quote(predicate.op)}${predicate.value ? `, value: ${renderValue(predicate.value, ir)}` : ""} },`);
      }
      lines.push(`    ]);`);
    } else {
      const operation = operationById(catalogue, op.operationId);
      if (!operation) throw new RenderError(`Operation "${op.operationId}" is not in the evidence; the policy should have rejected this plan.`);
      lines.push(`    const ${identifier(op.id)} = ${renderRequest(op, operation, ir)};`);

      // The body is only read when something actually looks at it: an assertion about a field, or a
      // later call taking a value from it. An unread body would be an unused variable in the spec.
      if (readsBodyOf(ir, op.id)) {
        lines.push(`    const ${identifier(op.id)}Body = await ${identifier(op.id)}.json();`);
      }
    }

    lines.push(`    await observe("step", { id: ${quote(op.id)}, kind: ${quote(op.kind)}, phase: "complete" });`);
    for (const assertion of assertionsByOp.get(op.id) ?? []) {
      const obligation = testCase.obligations.find((candidate) => candidate.id === assertion.obligation);
      lines.push(`    // ${assertion.obligation} — ${comment(obligation?.text ?? "")}`);
      lines.push(`    ${renderAssertion(assertion, ir, catalogue)}`);
    }
  }

  lines.push(`  });`);
}

/**
 * The operation a UI assertion follows.
 *
 * It belongs after the last action of *its own step* — not after the last action on the screen,
 * which an earlier version did and which put "the code field is shown" (step 1) after step 2 had
 * already filled the form and clicked Save. The test still passed, and said nothing true: an
 * assertion in the wrong place proves the wrong thing.
 */
function lastOpBefore(ir: TestIr, assertion: Extract<IrAssertion, { kind: "assert.ui.element" }>, step: number | undefined): string | undefined {
  const candidates = ir.ops.filter((op) => (op.kind === "ui.goto" || op.kind === "ui.act") && op.screen === assertion.screen);
  const withinStep = step === undefined ? candidates : candidates.filter((op) => !("step" in op) || op.step === undefined || op.step <= step);
  return (withinStep[withinStep.length - 1] ?? candidates[candidates.length - 1] ?? ir.ops[ir.ops.length - 1])?.id;
}

/** Every value the plan uses, wherever it appears. */
function allValues(ir: TestIr): IrValue[] {
  const fromOps = ir.ops.flatMap((op) => {
    if (op.kind === "auth.api") return Object.values(op.body ?? {});
    if (op.kind === "auth.header") return [op.token];
    if (op.kind === "auth.unavailable") return [];
    if (op.kind === "db.read") return op.where.flatMap((predicate) => (predicate.value ? [predicate.value] : []));
    if (op.kind === "ui.act") return op.value ? [op.value] : [];
    if (op.kind === "ui.goto") return [];
    return Object.values({ ...op.pathParams, ...op.query, ...op.headers, ...op.body });
  });
  return [...fromOps, ...ir.assertions.flatMap((assertion) => ("value" in assertion && assertion.value ? [assertion.value] : []))];
}

const usesTestData = (ir: TestIr, name: string): boolean =>
  allValues(ir).some((value) => ("testData" in value && value.testData === name) || ("uniqueTestData" in value && value.uniqueTestData === name));

function uniqueDataConstraints(ir: TestIr, catalogue: EvidenceCatalogue): Map<string, number | undefined> {
  const constraints = new Map<string, number | undefined>();
  for (const op of ir.ops) {
    if (op.kind !== "api.request") continue;
    const operation = operationById(catalogue, op.operationId);
    for (const [fieldName, value] of Object.entries(op.body ?? {})) {
      if (!("uniqueTestData" in value)) continue;
      const field = operation?.requestBody?.fields.find((candidate) => candidate.path === fieldName);
      constraints.set(value.uniqueTestData, field?.maxLength);
    }
  }
  return constraints;
}

/** Does anything read this operation's response body? */
function readsBodyOf(ir: TestIr, opId: string): boolean {
  const readsFrom = allValues(ir).some((value) => "from" in value && value.from === opId);
  const assertsField = ir.assertions.some((assertion) => assertion.kind === "assert.body.field" && assertion.of === opId);
  const comparesAgainst = ir.assertions.some((assertion) => "value" in assertion && assertion.value && "from" in assertion.value && assertion.value.from === opId);
  return readsFrom || assertsField || comparesAgainst;
}

function renderValue(value: IrValue, ir?: TestIr): string {
  if ("literal" in value) return JSON.stringify(value.literal);
  if ("testData" in value) return identifier(value.testData);
  if ("uniqueTestData" in value) return identifier(value.uniqueTestData);
  // A database read hands back rows, an API call hands back a body. Both are read by path.
  const source = ir?.ops.find((op) => op.id === value.from);
  if (source?.kind === "db.read") return `${identifier(value.from)}[0]?.[${quote(value.path)}]`;
  return fieldAccessor(identifier(value.from), value.path);
}

function renderMap(values: Record<string, IrValue> | undefined, ir?: TestIr): string | undefined {
  const entries = Object.entries(values ?? {});
  if (entries.length === 0) return undefined;
  return `{ ${entries
    .map(([name, value]) => {
      const rendered = renderValue(value, ir);
      // `{ code }` rather than `{ "code": code }` when the two are already the same word.
      return rendered === name ? name : `${quote(name)}: ${rendered}`;
    })
    .join(", ")} }`;
}

function renderRequest(op: Extract<IrOperation, { kind: "api.request" }>, operation: ApiOperation, ir?: TestIr): string {
  const placeholders = pathPlaceholders(operation.pathTemplate);
  const args = placeholders.map((placeholder) => renderValue(op.pathParams![placeholder]!, ir));
  const options: string[] = [];
  const query = renderMap(op.query, ir);
  const headers = renderMap(op.headers, ir);
  const body = renderMap(op.body, ir);
  if (query) options.push(`params: ${query}`);
  if (headers) options.push(`headers: ${headers}`);
  if (body) options.push(`data: ${body}`);

  const callArgs = [...args, ...(options.length > 0 ? [`{ ${options.join(", ")} }`] : [])];
  return `await api.${identifier(operation.operationId)}(${callArgs.join(", ")})`;
}

/** One matcher, one expectation. The mapping is fixed here so no two assertions can mean the same thing differently. */
function renderMatcher(accessor: string, matcher: IrMatcher, value: IrValue | undefined, ir?: TestIr): string {
  switch (matcher) {
    case "equals":
      return `expect(${accessor}).toEqual(${renderValue(value!, ir)});`;
    case "notEquals":
      return `expect(${accessor}).not.toEqual(${renderValue(value!, ir)});`;
    case "contains":
      return `expect(String(${accessor})).toContain(String(${renderValue(value!, ir)}));`;
    case "matches":
      return `expect(String(${accessor})).toMatch(new RegExp(String(${renderValue(value!, ir)})));`;
    case "exists":
      return `expect(${accessor}).toBeDefined();`;
    case "absent":
      return `expect(${accessor}).toBeUndefined();`;
  }
}

const fieldAccessor = (subject: string, path: string): string =>
  `${subject}Body${path.split(".").map((part) => (part.endsWith("[]") ? `[${quote(part.slice(0, -2))}][0]` : `[${quote(part)}]`)).join("")}`;

function renderAssertion(assertion: IrAssertion, ir: TestIr, catalogue: EvidenceCatalogue): string {
  if (assertion.kind === "assert.ui.element") return renderUiState(assertion, catalogue, ir);
  const subject = identifier(assertion.of);
  switch (assertion.kind) {
    case "assert.status":
      return `expect(${subject}.status()).toBe(${assertion.status});`;
    case "assert.body.field":
      return renderMatcher(fieldAccessor(subject, assertion.path), assertion.matcher, assertion.value, ir);
    case "assert.header":
      return renderMatcher(`${subject}.headers()[${quote(assertion.name.toLowerCase())}]`, assertion.matcher, assertion.value, ir);
    case "assert.db.rows":
      return renderRowCount(subject, assertion.expectation, assertion.count);
    case "assert.db.field":
      return renderMatcher(`${subject}[0]?.[${quote(assertion.column)}]`, assertion.matcher, assertion.value, ir);
  }
}

/**
 * A web-first assertion every time.
 *
 * `expect(locator).toBeVisible()` retries until it holds or times out; reading a boolean and
 * asserting on it does not, and is the usual source of a suite that passes locally and flakes in
 * CI. The renderer never emits the second kind.
 */
function renderUiState(assertion: Extract<IrAssertion, { kind: "assert.ui.element" }>, catalogue: EvidenceCatalogue, ir: TestIr): string {
  const screen = screenByName(catalogue, assertion.screen);
  if (!screen) throw new RenderError(`Screen "${assertion.screen}" is not in the approved contract; the policy should have rejected this plan.`);
  const locator = `expect(${identifier(screen.name)}Page.${identifier(assertion.element)})`;

  switch (assertion.state) {
    case "visible":
      return `await ${locator}.toBeVisible();`;
    case "hidden":
      return `await ${locator}.toBeHidden();`;
    case "enabled":
      return `await ${locator}.toBeEnabled();`;
    case "disabled":
      return `await ${locator}.toBeDisabled();`;
    case "checked":
      return `await ${locator}.toBeChecked();`;
    case "hasText":
      return `await ${locator}.toContainText(String(${renderValue(assertion.value!, ir)}));`;
    case "hasValue":
      return `await ${locator}.toHaveValue(String(${renderValue(assertion.value!, ir)}));`;
  }
}

/** "The row is there", "it is not", "there are exactly n" — the three things a count can mean. */
function renderRowCount(subject: string, expectation: "exists" | "absent" | "exactly", count: number | undefined): string {
  switch (expectation) {
    case "exists":
      return `expect(${subject}.length).toBeGreaterThan(0);`;
    case "absent":
      return `expect(${subject}).toHaveLength(0);`;
    case "exactly":
      return `expect(${subject}).toHaveLength(${count});`;
  }
}
