import type { TargetConfig } from "./config/targetConfig.js";
const marker = "/* @generated by spec-generation-agent */\n";

export function configSource(target: TargetConfig): string {
  return marker + `import { defineConfig } from '@playwright/test';
export default defineConfig({ testDir: '.', testMatch: '*.spec.ts', retries: 0, workers: 1,
  outputDir: process.env.QA_OBSERVATION_DIR ?? './results',
  use: { baseURL: process.env.SPECGEN_UI_BASE_URL ?? ${JSON.stringify(target.uiBaseUrl ?? target.baseUrl)},
    ${target.auth.storageState ? "storageState: process.env.QA_STORAGE_STATE," : ""}
    trace: 'retain-on-failure', screenshot: 'only-on-failure', extraHTTPHeaders: ${JSON.stringify(target.headers)} } });
`;
}

export function observationSource(): string {
  return marker + `import { test, type APIResponse } from '@playwright/test';
export function redact(value: unknown): unknown {
  if (typeof value === 'string') return value.replace(/Bearer\\s+[^\\s"']+/gi, 'Bearer [REDACTED]').slice(0, 20000);
  if (Array.isArray(value)) return value.slice(0, 100).map(redact);
  if (value && typeof value === 'object') {
    const result: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) result[key] = /password|secret|token|authorization|cookie|api.?key/i.test(key) ? '[REDACTED]' : redact(item);
    return result;
  }
  return value;
}
export async function observe(kind: string, data: unknown): Promise<void> {
  await test.info().attach('qa-observation', { body: Buffer.from(JSON.stringify({ kind, at: new Date().toISOString(), data: redact(data) })), contentType: 'application/json' });
}
export async function observeResponse(operationId: string, response: APIResponse): Promise<void> {
  let body: unknown;
  try { body = await response.json(); } catch { body = '[non-JSON response omitted]'; }
  const address = new URL(response.url()); address.search = ''; address.hash = '';
  await observe('api', { operationId, url: address.toString(), status: response.status(), headers: response.headers(), body });
}
`;
}

export function fixtureSource(target: TargetConfig, usesUi: boolean): string {
  return marker + `import { test as base, expect, type APIRequestContext } from '@playwright/test';
import { observe } from './observations.js';
export { expect };
export const test = base.extend<{ apiContext: APIRequestContext; observations: void }>({
  apiContext: async ({ playwright }, use) => {
    const context = await playwright.request.newContext({ baseURL: process.env.SPECGEN_BASE_URL ?? ${JSON.stringify(target.baseUrl)}, extraHTTPHeaders: ${JSON.stringify(target.headers)} });
    try { await use(context); } finally { await context.dispose(); }
  },
  ${usesUi ? `observations: [async ({ page }, use, info) => {
    await use();
    // These probes only read the page. They never repeat a business action.
    try { await observe('page', { url: page.url().split('?')[0], title: await page.title() }); } catch {}
    if (info.status !== info.expectedStatus) {
      try { await info.attach('ui-screenshot', { body: await page.screenshot(), contentType: 'image/png' }); } catch {}
    }
  }, { auto: true }],` : ""}
});
`;
}

export function uniqueDataSource(): string {
  return marker + `import { randomUUID } from 'node:crypto';
export function uniqueValue(base: string, maxLength?: number): string {
  const token = randomUUID().replaceAll('-', '').slice(0, maxLength === undefined ? 16 : Math.min(16, maxLength));
  if (maxLength === undefined) return base + '-' + token;
  const separator = maxLength > token.length ? '-' : '';
  return base.slice(0, Math.max(0, maxLength - token.length - separator.length)) + separator + token;
}
`;
}
