import type { AuthorContext, Scenario, Target, TestType } from "../stages/test-author.js";

export function designRetryPrompt(response: unknown, problems: string[]): string {
  return `\nPrevious JSON: ${JSON.stringify(response)}\nCorrect that complete JSON object. Fix these problems: ${problems.slice(0, 24).join("; ")}. Preserve supported content, use only known graph IDs and criterion labels, and return JSON only.`;
}

export function testPlanPrompt(context: AuthorContext, candidates: TestType[], source: string, targets: Record<TestType, Target[]>): string {
  return `Author plan for Story ${context.story.id}. Return one JSON object. Required shapes: objective and scopeSummary are strings; inScope is [{"nodeId":"known graph ID","reason":"text"}]; outOfScope is [{"item":"text","reason":"text"}]; approaches is [{"testType":"one applicable type","purpose":"text","focus":"one string","entryCriteria":["text"],"exitCriteria":["text"]}]; inapplicable is [{"testType":"candidate type","reason":"why no meaningful test is supported"}]; risks is [{"name":"text","description":"text","likelihood":"high|medium|low","impact":"high|medium|low","mitigation":"text"}]; environments, testDataNeeds, assumptions, and openQuestions are arrays of strings. Use [] when a field has no supported content. Candidate types: ${candidates.join(", ")}. Choose exactly one approach or inapplicable reason for each candidate. A graph mention alone does not prove that a full suite is needed. Identify changed behavior, affected users and systems, failure impact, and why each chosen approach matters. Treat risks as evidence-based possibilities, not observed defects. Do not invent environments or data. Candidate targets: ${JSON.stringify(targets)}. Sources: ${source}\nApproved graph: ${JSON.stringify({ nodes: context.nodes, edges: context.edges })}`;
}

export function testScenariosPrompt(
  testType: TestType, context: AuthorContext, coverIds: string[], exerciseIds: string[],
  batch: Target[], candidateScenarios: AuthorContext["nodes"], priorScenarios: Scenario[], source: string, passageIds: string[],
): string {
  return `Author scenarios for ${testType} Story ${context.story.id}. Return JSON {reusedScenarios:[{id,targetIds}],newScenarios:[{name,description,expectedOutcome,priority,evidence,sourceId,category,riskRationale,targetIds,acceptanceCriteria,coversNodeIds,exercisesNodeIds}]}. For each target consider supported normal, invalid, boundary, state, integration, recovery, and regression behavior. Choose only meaningful categories with a stated observable outcome; do not invent rules to fill a category. Set category to one of normal|invalid|boundary|state|integration|recovery|regression and explain the risk in riskRationale. Every new scenario must have priority exactly "critical", "high", "medium", or "low"; evidence must be ONE string copied contiguously from the passage identified by sourceId, not an array or paraphrase. If a target lacks a test oracle, leave it uncovered so the validator records a gap. Passage IDs: ${passageIds.join(", ")}. acceptanceCriteria must be an array containing only these labels: ${context.criteria.map((item) => item.label).join(", ") || "none"}. Use [] for no criteria or node references. targetIds must copy only these exact IDs, character for character: ${JSON.stringify(batch.map((item) => item.id))}. coversNodeIds may contain only ${JSON.stringify(coverIds)}; exercisesNodeIds may contain only ${JSON.stringify(exerciseIds)}. Endpoint and Operation IDs belong in exercisesNodeIds, never coversNodeIds. Reuse an existing scenario if it already covers a target. Create missing scenarios before test cases. Cover every target that has a supported outcome. Targets: ${JSON.stringify(batch)}. Existing graph scenarios: ${JSON.stringify(candidateScenarios)}. Earlier authored scenarios: ${JSON.stringify(priorScenarios)}. Source: ${source}`;
}

export function testCasesPrompt(testType: TestType, scenario: Scenario, criteria: AuthorContext["criteria"], existingCases: AuthorContext["nodes"], source: string,
  validateIds: string[], exerciseIds: string[]): string {
  return `Author test cases for ${testType} scenario ${JSON.stringify(scenario)}. Return JSON {reusedCaseIds:["existing id"],newCases:[{name,objective,caseKind,priority,preconditions,testData,steps:[{action,expectedResult,expectedResultEvidence}],acceptanceCriteria,validatesNodeIds,exercisesNodeIds,automationCandidate,automationNotes,evidence,sourceId,route?}]}. Each priority is exactly "critical", "high", "medium", or "low". Each acceptanceCriteria is an array of labels from ${criteria.map((item) => item.label).join(", ") || "none"}. validatesNodeIds may contain only these Requirement, BusinessRule, or Constraint IDs: ${JSON.stringify(validateIds)}. exercisesNodeIds may contain only these system or business entity IDs: ${JSON.stringify(exerciseIds)}. Copy IDs exactly; use [] when there is no suitable ID. A Story is linked by its acceptance criteria and test hierarchy, not by validatesNodeIds. Endpoint, Operation, and Module IDs belong in exercisesNodeIds. Each evidence and expectedResultEvidence is ONE contiguous quote from the source named by sourceId. Tie each precondition, test datum, action, and observable expected result to that source. Use [] for unspecified preconditions or data. Do not write vague results such as 'works correctly' or 'expected outcome is observed'. If the source lacks an executable action or test oracle, return no new case so the validator records a gap. Do not invent routes, fields, or outcomes. Mark automationCandidate true only with supported automation details. Reuse cases only if explicitly supported. Existing cases: ${JSON.stringify(existingCases)}. Source: ${source}`;
}
